### ISSUE TITLE
CMS pattern template: set pattern PDF selection as not required

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#107]
# Bug report

**What is the current behavior?**
Pattern PDF selection is required

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Pattern PDF selection not required

**Other relevant information:**
There is an instance where no PDF is required (any other mask). I cannot update other content page when a PDF is required. Does not make sense to have a PDF.

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by gvan12** [comment]
I think this is resolved - will leave open until you can confirm.

**Comment by cqrmskgiub** [comment]
Works perfectly, thanks!
