### ISSUE TITLE
Semi-low priority: front page CTAs not centered on desktop

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#109]
# Bug report

**What is the current behavior?**
I want to... Volunteer   Get Masks not centered

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
CTAs centered

**Other relevant information:**
![image](https://user-images.githubusercontent.com/29091366/79206564-5c2a7500-7df4-11ea-9966-a86c38f69c3b.png)

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by gvan12** [comment]
which do you prefer?
1.

![image](https://user-images.githubusercontent.com/7634717/79228718-8a757800-7e27-11ea-976f-1b3070f0fdb4.png)

2.

![image](https://user-images.githubusercontent.com/7634717/79228744-96613a00-7e27-11ea-91d2-320fe5538405.png)

3.

![image](https://user-images.githubusercontent.com/7634717/79228773-a0833880-7e27-11ea-865c-ad67580865fa.png)

**Comment by cqrmskgiub** [comment]
Is there a reason option 3 has a big margin on the left?
