### ISSUE TITLE
Navbar items---rearrange + About dropdown

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#115]
## Feature request

**What is the expected behavior?**
navbar order change

**What is motivation or use case for adding/changing the behavior?**
for fundraising push, to allow donors to quickly see who we are/what we do

**How should this be implemented in your opinion?**
Volunteer
Resources
Press
About Us
Donate

Also combine with #90. #89 can be combined too but less important to do right now right now.

Also make About Us a dropdown with FAQ nested under it. "About Us" navbar item links to the "About Us" page.

**Are you willing to work on this yourself?**
can't

**Comment by cqrmskgiub** [comment]
Also add "Partners" as a dropdown under About Us.

About Us ----> About Us page

drops down to

Partners ----> Partners page
FAQ ----> FAQ page

**Comment by cqrmskgiub** [comment]
No longer urgent.

**Comment by gvan12** [comment]
let me know if what we have now solves this - it's not a nav link that's also an onHover - but that actually shakes out to be really bad accessibility so anything that's a dropdown is _not_ a link. Instead the link is the first option in the dropdown.

We can uplift this later to be onHover - maybe that's what this ticket can morph into. Maybe it's better to just make a new ticket for that.

**Comment by cqrmskgiub** [comment]
No need to be hover, we can keep this as is. Great work, thank you <3

Request from the steering committee: Change "Fundraising" navbar item to "Help Us ❤️"

Actual request was “Help the Sewists” or “Why you should give” but both have too many letters I think. Open to other suggestions.

**Comment by gvan12** [comment]
![image](https://user-images.githubusercontent.com/7634717/79716582-bfa51e80-829c-11ea-82c3-72d8aa9967fc.png)

**Comment by gvan12** [comment]
changed in 00ec510.
