### ISSUE TITLE
URGENT: Donate page - put donate form under all CMS content

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#118]
## Feature request

**What is the expected behavior?**
CMS content shows above donate form on Donate page

**What is motivation or use case for adding/changing the behavior?**
To allow CMS manager to edit the Donate page better

**How should this be implemented in your opinion?**
up to you

**Are you willing to work on this yourself?**
can't

**Comment by gvan12** [comment]
resolved in 64fa265
