### ISSUE TITLE
'Resources' navbar: change "Masks Kits" to "Buy Interfacing" & link to external site (to be provided by 4/21)

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#122]
## Feature request

**What is the expected behavior?**
Change "Masks Kits" to "Buy Interfacing"
Link "Buy Interfacing" to external site
URL of external site to be provided either 4/20 or 4/21.

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
can't

**Comment by gvan12** [comment]
https://thermowebmasksnow.com/
