### ISSUE TITLE
Add Volunteer FAQs Page

### ISSUE THREAD

**Issue by gvan12** [RosieSews/masksnow#57]
## Feature request

**What is the expected behavior?**
. Add one

**What is motivation or use case for adding/changing the behavior?**
the currenty faq isn't specific enough to address the needs of our volunteers

**How should this be implemented in your opinion?**
checkout out these two PR's for examples: https://github.com/RosieSews/masksnow/pull/17
https://github.com/RosieSews/masksnow/pull/16

**Are you willing to work on this yourself?**
yes

**Comment by gvan12** [comment]
To be clear - this is simply making a new directory in `/pages` called `volunteer-faq` with a .md file similar to other pages. Then connect the rest of the CMS files. Reference the above mentioned PR's for examples.

**Comment by cqrmskgiub** [comment]
Making a volunteer portal on fresh desk. Will request new navbar when ready.
