### ISSUE TITLE
Updated pattern page w/ profpin video - do not publish until video is live on YouTube (9am ET? not sure?)

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#58]
I used the CMS to throw something together really quickly.

Please link the img 3-layer-mask-download.png to https://masksnow.org/docs/CFCMask_3_27.pdf (could not figure out how to get that right in markdown)

**Comment by gvan12** [comment]
it's not a problem now - but for future reference, any changes made in the CMS are published immediately so that video was live for about an hour. I've removed it and will put it back up when given the go-ahead. Also will make that image a link to the file as requested.

**Comment by cqrmskgiub** [comment]
Ahh fuck my bad, didn't know it was immediate
