### ISSUE TITLE
It's not obvious that a page navigation happened

### ISSUE THREAD

**Issue by Shelob9** [RosieSews/masksnow#72]
# Bug report

**What is the current behavior?**

The page refresh is very fast, but it's not obvious it happened as the top of the page does not change.

# Solution

In Slack https://rosiesews.slack.com/archives/C010RDJL7AA/p1585845125464700 we discussed putting the page title above the call to action:

For desktop: 

![desktop](https://user-images.githubusercontent.com/1994311/78274964-f9290c00-74de-11ea-97b7-c3989e3e7e4f.jpg)

For mobile:
![mobile](https://user-images.githubusercontent.com/1994311/78274963-f9290c00-74de-11ea-936c-3009e1d9df04.jpg)

Also, the blue bar should go away. 

https://rosiesews.slack.com/archives/C010RDJL7AA/p1585845379466000

**Comment by Shelob9** [comment]
I have PR #71 open to change headings from h1 to h2s, this will likely replace that PR. But I want to make sure I keep titles as h1s.

**Comment by gvan12** [comment]
closing as this has been addressed in some of the other updates that've been made.
