### ISSUE TITLE
front page edit to make it more obvious that we accept all mask patterns

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#88]
## Feature request

**What is the expected behavior?**
on front page, in section "Donate Masks" add text under "YOUR STATE LEAD WILL EMAIL YOU WITH DIRECTIONS ABOUT HOW & WHERE". text to say "we will donate all masks no matter what pattern you use" or something of the sort.

**What is motivation or use case for adding/changing the behavior?**
to make sure people know that we donate all masks, they don't *have* to use our pattern.

**How should this be implemented in your opinion?**
same as above

**Are you willing to work on this yourself?**
can't

**Comment by cqrmskgiub** [comment]
alternatively or additionally, under "get the pattern" it can say (or use any pattern of your choosing)

**Comment by alfdocimo** [comment]
Hi @cqrmskgiub! First of all nice to meet you! I've taken on this issue and have added both texts to each section:
**Get the pattern**
![image](https://user-images.githubusercontent.com/22222078/79046672-a3f1a680-7c12-11ea-81af-4cafee60865f.png)
**Donate Masks**
![image](https://user-images.githubusercontent.com/22222078/79046705-cf749100-7c12-11ea-9999-937854af44a1.png)

I've used the same styles as the warning (*PERSONAL USE ONLY) text for consistency.

Could this be enhanced in any way? color, position, padding? I could use some advice.

Also: please ignore the images having a weird non-transparent background. Seems to be a gatsby issue for windows users 😰 [https://github.com/gatsbyjs/gatsby/issues/14497]

**Comment by gvan12** [comment]
I'll wait until @cqrmskgiub responds for a definitive answer - but if you could either add a prop to the component so it can flex it's styling to _not_ have margin-left in this scenario I think that would be better. Color, size, style, all look good to me!

**Comment by cqrmskgiub** [comment]
Agree with Garrett, currently the added text is aligned with the bullet
text, would like the text to be aligned with the bullets under "get
pattern" (and text under "donate masks").

Please change the new text in "donate masks" to: "Every mask made will be
donated, no matter what pattern you use". Also would prefer to have more
margin or padding above this text.

Thanks so much!!

**Comment by gvan12** [comment]
It's using the style for the warning, do you want those warning texts to
have more top Margin as well? Can be different just need to know for to
implement.

**Comment by cqrmskgiub** [comment]
On second thought!!

Only for the "every mask made text", change it to same style as "your state
lead will email you" and link it to:
https://rosiesews.freshdesk.com/support/solutions/articles/61000268414-can-i-use-a-different-pattern-than-what-you-provide-

**Comment by gvan12** [comment]
Thanks! Should be set on this now!

**Comment by alfdocimo** [comment]
Got it! created a PR for this. Please let me know if I can improve anything! (:
