### ISSUE TITLE
navbar "media" dropdown

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#90]
## Feature request

**What is the expected behavior?**
navbar item called "media" which is a dropdown menu item

**What is motivation or use case for adding/changing the behavior?**
put all relevant media type things in one location

**How should this be implemented in your opinion?**
navbar "media" drops down to:
1) PSAs
2) In the News
3) Blog

**Are you willing to work on this yourself?**
cant

**Comment by alfdocimo** [comment]
Hey there! I believe this implementation should also work for #89, right?

Also, I have a couple of questions about this.

I understand that we'd be trying to accomplish something like this?

![image](https://user-images.githubusercontent.com/22222078/79196319-286d4080-7e30-11ea-83d1-fcea7c59b555.png)

https://wireframe.cc/ACTMlg

* Should the _PSAs_ option show only on the dropdown or should we have it both on the _media_ dropdown as well as in the _navbar_ itself?

* Any chance we could use an open-source dropdown component? That is of course if the API allows us to customize it as we want (both on style and usability) 

* Should the dropdown be triggered on _click_ or on _hover_? 

Thanks!

**Comment by cqrmskgiub** [comment]
Yes, it should work for 89 too :)

PSAs should only show under the dropdown

I can't answer the open-source dropdown component question

Trigger on hover please :)

navbar order:

Volunteer
Resources
FAQs
Media

**Comment by gvan12** [comment]
Use MUIs drop-down for this. We've been planning on including it for
several other PRs, and it plays nicely with styled-components.

**Comment by cqrmskgiub** [comment]
Update:

Navbar item should be called "Press"

Drops down to:

PSAs
Media Hits
Press Releases
Blog

**Comment by cqrmskgiub** [comment]
Blog should link to: https://medium.com/themasksnowcoalition

PSAs, Media Hits, Press Releases are ready in CMS

**Comment by cqrmskgiub** [comment]
Alternatively, the navbar item "Press" could direct to "Press Releases" page, with dropdowns as:

PSAs
Media Hits
Blog
