### ISSUE TITLE
iPhone SE: front page CTA too wide for screen

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#93]
# Bug report

**What is the current behavior?**
Front page can scroll to right slightly due to CTA buttons

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
No scroll, buttons fit

**Other relevant information:**
iPhone SE chrome
![CDD85157-CD16-4BE5-BEA0-83A2484FADFE](https://user-images.githubusercontent.com/29091366/79032714-844c7680-7b5d-11ea-9e75-12071273326c.png)

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by cqrmskgiub** [comment]
Additionally, less top/bottom padding would be nice too

**Comment by jamesonhill** [comment]
i can pick this up
